### ISSUE TITLE
Repository als GitHub-Template einstellen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yak#34]
Vorschlag: Im yak-Repository unter "Settings" den Haken "Template" aktivieren, damit dieses Repository direkt als Grundlage für ein neues Projekt genutzt werden kann.

**Comment by alxndr-w** [comment]
Einstellung:

![image](https://user-images.githubusercontent.com/3855487/161785638-1278fad0-43f4-40bf-a063-60272e4d3f79.png)

Ergebnis:

![image](https://user-images.githubusercontent.com/3855487/161785727-afe8d93d-2cde-4c8b-978e-d765fde24a20.png)

![image](https://user-images.githubusercontent.com/3855487/161785784-e9985568-364e-4576-9bf8-f9772f37f98a.png)

**Comment by gharlan** [comment]
Wobei die Frage ist, ob es so gut passt, weil man ja eigentlich erst das Setup durchläuft.
Gibt es bei den Templates die Möglichkeit, automatisch ein Script (Action) ablaufen zu lassen, vor dem initialen Commit?

**Comment by alxndr-w** [comment]
@gharlan da muss ich passen. 

Ich weiß nur: Man kann solche Skripte auch manuell starten und das wäre ja auch notwendig, um bspw. die Liste vorinstallierter Addons nochmal anpassen zu können...

**Comment by gharlan** [comment]
Ja stimmt, automatisiert passt daher vermutlich nicht.
Mich stört dann bisschen, dass man erst einen init-commit hat mit dem template-inhalt, und erst mit dem nächsten commit dann die eigentliche struktur erhält (nachdem man das setup ausgeführt hat). Aber ich bin auch bisschen ein Ordentliche-Commit-History-Fetischist.

Daher würde ich den Button dann wahrscheinlich nicht nutzen. Aber andererseits schadet der Button auch nicht.
Soll @tbaddade entscheiden.

**Comment by tbaddade** [comment]
Unser aktuelles Vorgehen kurz beschrieben:

1. Repo hier als Zip herunterladen und auf Platte entpacken
2. Presetup durchlaufen lassen
3. Redaxo Setup durchlaufen
4. YDeploy Diff
5. erster möglicher Commit

Wäre es denn möglich, das Repo hier auch als Basis für Gitlab-Projekte zu nutzen? Könnten wir dort das Presetup automatisch durchlaufen lassen?

Wenn der Button nicht wieder schadet und irgendwie kein Mehraufwand entsteht können wir das gern aktivieren.
